"""feat: add company_id to sale model

Revision ID: 567cff43f1e1
Revises: d73d1f03fb02
Create Date: 2026-05-20 16:29:03.763524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567cff43f1e1'
down_revision: Union[str, Sequence[str], None] = 'd73d1f03fb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'company_id')
    # ### end Alembic commands ###
